server:
  port: 8083

spring:
  application:
    name: ride-management-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27019/ridelink_rides}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

jwt:
  secret: ${JWT_SECRET:RideLinkSuperSecretKeyForJWTTokenGeneration2024MustBeLongEnough}
  expiration: 86400000

service:
  driver-url: ${DRIVER_SERVICE_URL:http://localhost:8082}
  fare-url: ${FARE_SERVICE_URL:http://localhost:8084}

rabbitmq:
  exchange: ride.exchange
  routing-key:
    completed: ride.completed

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
